In [1]:
import pandas as pd
import numpy as np
from scipy import sparse
from recovery_model.system_builder import System

In [2]:
# from itertools import product, chain
# from collections import defaultdict
# from dataclasses import dataclass
# from operator import mul
# from functools import reduce
# from pprint import pprint, pformat
# from typing import Literal
# import json

In [3]:
composition_dct = {
    "url": "data/basic/Toy_WEEE_Composition.xlsx",  # "../../data/WEE/Toy_WEEE_Composition.xlsx",
    "sheet": {
        "P_C": {
            "index": ("Flow", "Category", "Component"),
            "columns": ("Flow", "Category"),
            "data": "Share_Component",
        },
        "P_M": {
            "index": ("Flow", "Category", "Material"),
            "columns": ("Flow", "Category"),
            "data": "Share_Material",
        },
        "PC_E": {
            "index": ("Flow", "Category", "Component", "Element"),
            "columns": ("Flow", "Category", "Component"),
            "data": "Share_element",
        },
        "PM_E": {
            "index": ("Flow", "Category", "Material", "Element"),
            "columns": ("Flow", "Category", "Material"),
            "data": "Share_element",
        },
    },
    "mapper": {
        "Flow": "flows",
        "Category": "products",
        "Component": "components",
        "Material": "materials",
        "Element": "elements",
        "Share_Component": "data",
        "Share_Material": "data",
        "Share_element": "data",
        "Year": "year",
    },
}

tc_dct = {
    "url": "data/basic/Toy_WEEE_TCs.xlsx",  #  "../../data/WEE/Toy_WEEE_TCs.xlsx",
    "crossboundary_inflows": ("WEEE_INFLOW",),
    "sheet": {
        "Toy_WEEE_TCs": {
            "flows": ("input_flow", "output_flow"),
            "data": "value",
        },
    },
    "mapper": {
        "value": "data",
        "Year": "year",
    },
}

inputs_dct = {
    "url": "data/basic/Toy_WEEE_inputs.xlsx",  # "../../data/WEE/Toy_WEEE_inputs.xlsx",
    "sheet": {
        "Toy_WEEE_inputs": {
            "index": ("input_flow", "Category"),
            "columns": None,
            "data": "mass_(tonnes)",
        },
    },
    "unit": "tonnes",
    "mapper": {
        "input_flow": "flows",
        "Category": "products",
        "mass_(tonnes)": "data",
        "Year": "year",
    },
}

To do:

- set ones on diagonal
- set y (mass)
- solve and validate


In [4]:
weee = System(composition_dct=composition_dct, inputs_dct=inputs_dct, tc_dct=tc_dct)

In [5]:
weee.index

MultiIndex([('WEEE_2RM_mechRec1Smelter_CuScrap',      -1, ...),
            ('WEEE_2RM_mechRec1Smelter_CuScrap',      -1, ...),
            ('WEEE_2RM_mechRec1Smelter_CuScrap',      -1, ...),
            ('WEEE_2RM_mechRec1Smelter_CuScrap',      -1, ...),
            ('WEEE_2RM_mechRec1Smelter_CuScrap',      -1, ...),
            ('WEEE_2RM_mechRec1Smelter_CuScrap',      -1, ...),
            ('WEEE_2RM_mechRec1Smelter_CuScrap',      -1, ...),
            ('WEEE_2RM_mechRec1Smelter_CuScrap',      -1, ...),
            ('WEEE_2RM_mechRec1Smelter_CuScrap',      -1, ...),
            ('WEEE_2RM_mechRec1Smelter_CuScrap',      -1, ...),
            ...
            (           'WEEE_wasteBinLandfill', 'Cat_2', ...),
            (           'WEEE_wasteBinLandfill', 'Cat_2', ...),
            (           'WEEE_wasteBinLandfill', 'Cat_2', ...),
            (           'WEEE_wasteBinLandfill', 'Cat_2', ...),
            (           'WEEE_wasteBinLandfill', 'Cat_2', ...),
            (           

In [6]:
weee.idx

flows   
flows                            products components     materials                 elements                                     
WEEE_2RM_mechRec1Smelter_CuScrap -1       -1             -1                        -1        WEEE_2RM_mechRec1Smelter_CuScrap  \
                                                                                   Al        WEEE_2RM_mechRec1Smelter_CuScrap   
                                                                                   Cu        WEEE_2RM_mechRec1Smelter_CuScrap   
                                                         AluminiumAlloyUnspecified -1        WEEE_2RM_mechRec1Smelter_CuScrap   
                                                                                   Al        WEEE_2RM_mechRec1Smelter_CuScrap   
...                                                                                                                       ...   
WEEE_wasteBinLandfill            Cat_2    PCBUnspecified -1                        Al                   WEEE_wasteBinLandfill   
                                                                                   Cu                   WEEE_wasteBinLandfill   
                                                         AluminiumAlloyUnspecified -1                   WEEE_wasteBinLandfill   
                                                                                   Al                   WEEE_wasteBinLandfill   
                                                                                   Cu                   WEEE_wasteBinLandfill   

                                                                                            products   
flows                            products components     materials                 elements            
WEEE_2RM_mechRec1Smelter_CuScrap -1       -1             -1                        -1             -1  \
                                                                                   Al             -1   
                                                                                   Cu             -1   
                                                         AluminiumAlloyUnspecified -1             -1   
                                                                                   Al             -1   
...                                                                                              ...   
WEEE_wasteBinLandfill            Cat_2    PCBUnspecified -1                        Al          Cat_2   
                                                                                   Cu          Cat_2   
                                                         AluminiumAlloyUnspecified -1          Cat_2   
                                                                                   Al          Cat_2   
                                                                                   Cu          Cat_2   

                                                                                                 components   
flows                            products components     materials                 elements                   
WEEE_2RM_mechRec1Smelter_CuScrap -1       -1             -1                        -1                    -1  \
                                                                                   Al                    -1   
                                                                                   Cu                    -1   
                                                         AluminiumAlloyUnspecified -1                    -1   
                                                                                   Al                    -1   
...                                                                                                     ...   
WEEE_wasteBinLandfill            Cat_2    PCBUnspecified -1                        Al        PCBUnspecified   
                                                                                   Cu     

In [7]:
weee.flows

('WEEE_2RM_mechRec1Smelter_CuScrap',
 'WEEE_2RM_mechRec2Smelter_AlScrap',
 'WEEE_2RM_mechRec2Smelter_CuScrap',
 'WEEE_2RM_mechRecLampsSmelter_CuScrap',
 'WEEE_INFLOW',
 'WEEE_PVPanels',
 'WEEE_collected',
 'WEEE_generatedComplementaryMSW',
 'WEEE_generatedComplementaryMetalScrapExportedUndocumented',
 'WEEE_generatedDedicated',
 'WEEE_ironCircuit',
 'WEEE_lampsDirect_(without_LED)',
 'WEEE_largeEquipment',
 'WEEE_screensAndMonitors',
 'WEEE_smallEquipment',
 'WEEE_smallIT',
 'WEEE_temperatureExchangeEquipment',
 'WEEE_wasteBinIncineration',
 'WEEE_wasteBinLandfill')

In [8]:
weee.products

('Cat_1', 'Cat_2')

In [9]:
weee.materials

('AluminiumAlloyUnspecified',)

In [10]:
weee.elements

('Al', 'Cu')

In [12]:
print(weee)

{   'components': ('Cables', 'PCBUnspecified'),
    'elements': ('Al', 'Cu'),
    'flows': (   'WEEE_2RM_mechRec1Smelter_CuScrap',
                 'WEEE_2RM_mechRec2Smelter_AlScrap',
                 'WEEE_2RM_mechRec2Smelter_CuScrap',
                 'WEEE_2RM_mechRecLampsSmelter_CuScrap',
                 'WEEE_INFLOW',
                 'WEEE_PVPanels',
                 'WEEE_collected',
                 'WEEE_generatedComplementaryMSW',
                 'WEEE_generatedComplementaryMetalScrapExportedUndocumented',
                 'WEEE_generatedDedicated',
                 'WEEE_ironCircuit',
                 'WEEE_lampsDirect_(without_LED)',
                 'WEEE_largeEquipment',
                 'WEEE_screensAndMonitors',
                 'WEEE_smallEquipment',
                 'WEEE_smallIT',
                 'WEEE_temperatureExchangeEquipment',
                 'WEEE_wasteBinIncineration',
                 'WEEE_wasteBinLandfill'),
    'index': {   'components': {-1: 0, 'Cabl

In [17]:
cases = [
    ["WEEE_INFLOW", slice(None), "Cables", -1, -1],
    pd.IndexSlice["WEEE_INFLOW", "Cat_1", "Cables", :, :],
]

for row in cases:
    print(weee.index_loc(row), "\n")

[['WEEE_INFLOW' -1 'Cables' -1 -1]
 ['WEEE_INFLOW' 'Cat_1' 'Cables' -1 -1]
 ['WEEE_INFLOW' 'Cat_2' 'Cables' -1 -1]] 

[['WEEE_INFLOW' 'Cat_1' 'Cables' -1 -1]
 ['WEEE_INFLOW' 'Cat_1' 'Cables' -1 'Al']
 ['WEEE_INFLOW' 'Cat_1' 'Cables' -1 'Cu']
 ['WEEE_INFLOW' 'Cat_1' 'Cables' 'AluminiumAlloyUnspecified' -1]
 ['WEEE_INFLOW' 'Cat_1' 'Cables' 'AluminiumAlloyUnspecified' 'Al']
 ['WEEE_INFLOW' 'Cat_1' 'Cables' 'AluminiumAlloyUnspecified' 'Cu']] 



In [15]:
cases = [
    "WEEE_INFLOW",
    ["WEEE_INFLOW"],
    ("WEEE_INFLOW", "Cat_1"),
    ("WEEE_INFLOW", "Cat_1", "Cables", -1, -1),
    [("WEEE_INFLOW", "Cat_1", "Cables", -1, -1)],
    (["WEEE_INFLOW", "Cat_1", "Cables", -1, -1]),
    [["WEEE_INFLOW", "Cat_1", "Cables", -1, -1]],
    [
        ["WEEE_INFLOW", "Cat_1", "Cables", -1, -1],
        ["WEEE_INFLOW", "Cat_2", "Cables", -1, -1],
    ],
    ["WEEE_INFLOW", slice(None), "Cables", -1, -1],
    pd.IndexSlice["WEEE_INFLOW", "Cat_1", "Cables", :, :],
]

for row in cases:
    print(row)
    print(weee.get_indexer(row), "\n")

WEEE_INFLOW
[216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269] 

['WEEE_INFLOW']
[216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269] 

['WEEE_INFLOW']
[216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269] 

WEEE_INFLOW
[216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269] 

('WEEE_INFLOW',)
[216 217 218 219 220 221 222 223 224 22

In [19]:
int_idx = [240, 241, 242, 243, 244, 245]
list(weee.index_iloc(int_idx))

[('WEEE_INFLOW', 'Cat_1', 'Cables', -1, -1),
 ('WEEE_INFLOW', 'Cat_1', 'Cables', -1, 'Al'),
 ('WEEE_INFLOW', 'Cat_1', 'Cables', -1, 'Cu'),
 ('WEEE_INFLOW', 'Cat_1', 'Cables', 'AluminiumAlloyUnspecified', -1),
 ('WEEE_INFLOW', 'Cat_1', 'Cables', 'AluminiumAlloyUnspecified', 'Al'),
 ('WEEE_INFLOW', 'Cat_1', 'Cables', 'AluminiumAlloyUnspecified', 'Cu')]

---


In [20]:
df = pd.Index(list("abbc"))
df

Index(['a', 'b', 'b', 'c'], dtype='object')

In [24]:
idxs = df.get_loc("b")
df[idxs]

Index(['b', 'b'], dtype='object')

In [12]:
solution = weee.solve()
solution.to_csv("results/solution.csv")
solution

flows                             products  components      materials                  elements
WEEE_2RM_mechRec1Smelter_CuScrap  -1        -1              -1                         -1          0.0
                                                                                       Al          0.0
                                                                                       Cu          0.0
                                                            AluminiumAlloyUnspecified  -1          0.0
                                                                                       Al          0.0
                                                                                                  ... 
WEEE_wasteBinLandfill             Cat_2     PCBUnspecified  -1                         Al          0.0
                                                                                       Cu          0.0
                                                            AluminiumAlloyUnspec

In [13]:
np.vstack(
    [
        weee.tcs.tocoo().row,
        weee.tcs.tocoo().col,
        # weee.tcs.tocoo().data,
    ]
)

array([[   0,    1,    2, ..., 1023, 1024, 1025],
       [   0,    1,    2, ..., 1023, 1024, 1025]], dtype=int32)

In [14]:
tcs = weee.tcs.copy()
temp_tc = pd.DataFrame(tcs.toarray(), index=weee.index, columns=weee.index)


xbrdy_inflow = tc_dct["crossboundary_inflows"][0]
# for cat in ("Cat_1", "Cat_2", "Cat_3", "Cat_4a", "Cat_4b", "Cat_5", "Cat_6"):
#     idx_ax0 = pd.IndexSlice[xbrdy_inflow, cat, -1, -1]
#     idx_ax1 = pd.IndexSlice["products", cat]
#     temp_tc.loc[idx_ax0, idx_ax1] = 1

idx = pd.IndexSlice[xbrdy_inflow, :, :, :]
temp_tc.loc[idx, idx].to_csv("results/temp_tc.csv")

In [15]:
y = weee.y.copy()
temp_y = pd.DataFrame(y.toarray(), index=weee.index, columns=weee.columns)


temp_y.loc[idx].to_csv("results/temp_y.csv")

AttributeError: 'System' object has no attribute 'columns'

In [ ]:
(temp_tc * temp_y).loc[pd.IndexSlice[xbrdy_inflow, :, :, :]].to_csv("tc_dot_y.csv")

In [ ]:
A = temp_tc.loc[pd.IndexSlice[xbrdy_inflow, :, :, :]]
A.to_numpy().shape

In [ ]:
Y = temp_y.loc[pd.IndexSlice[xbrdy_inflow, :, :, :]]
Y.to_numpy().shape

In [ ]:
file = "data/test/TC Matrix Building v2.xlsx"
tcs = pd.read_excel(file, sheet_name="tc", header=None).values
y = pd.read_excel(file, sheet_name="y", header=None).values

In [ ]:
from scipy.sparse.linalg import spsolve
from scipy.sparse import csr_matrix, csc_matrix

A = csr_matrix(tcs)
Y = csr_matrix(y)
spsolve(A, Y)

In [ ]:
Afull = csr_matrix(tcs)
Afull.nonzero()

In [ ]:
np.vstack([Afull.nonzero(), Afull.data]).T

In [ ]:
def squarify(mat):
    max_dim = max(mat.shape)
    dims = np.array(mat.shape)
    new_shape = np.full(dims.shape, fill_value=max_dim)
    new_mat = np.zeros(new_shape)
    new_mat[: mat.shape[0], : mat.shape[1]] = mat
    return new_mat


new_A = squarify(A.to_numpy())

In [ ]:
res = new_A * Y.to_numpy()
pd.DataFrame(res, index=A.index, columns=Y.columns).to_csv("temp_res.csv")

In [ ]:
xbrdy_inflow = tc_dct["crossboundary_inflows"][0]
pp = pd.DataFrame(np.zeros(shape=(len(weee.index), len(weee.columns))), index=weee.index, columns=weee.columns)

prod = "Cat_1"
comp = slice(None)
mat = -1
idx_ax0 = pd.IndexSlice[xbrdy_inflow, prod, comp, mat]
idx_ax1 = pd.IndexSlice["products", prod]

pp.loc[idx_ax0, idx_ax1]

In [ ]:
def pruned(coo_mat, idxs, cols):
    csr_mat = coo_mat.tocsr()

    rows, _ = csr_mat.nonzero()
    unique_rows = np.sort(np.unique(rows))
    data = csr_mat[unique_rows, :].toarray()
    return pd.DataFrame(data=data, index=idxs[unique_rows], columns=cols)

In [ ]:
pruned(weee.y, weee.index, weee.columns).to_csv("test.csv")

In [ ]:
# i = weee.materials[0]
# i
rw = tuple([[-1, i, -1] for i in weee.materials])
cl = tuple([("materials", i) for i in weee.materials])
rw

<hr>

# Sparse matrices


In [16]:
rows1 = np.random.randint(6, size=10)
cols1 = np.random.randint(6, size=10)
data1 = np.random.randint(10, size=10)

print(np.array([rows1, cols1, data1]))

coo_arr1 = sparse.coo_array((data1, (rows1, cols1)), shape=(10, 6))
print(coo_arr1.shape)
csr_arr1 = coo_arr1.tocsr()
coo_arr1.toarray()

[[4 1 2 4 2 4 5 5 5 3]
 [0 4 0 1 4 0 4 0 3 2]
 [7 0 1 5 4 1 4 2 2 0]]
(10, 6)


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0],
       [8, 5, 0, 0, 0, 0],
       [2, 0, 0, 2, 4, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [17]:
rows2 = np.random.randint(6, size=10)
cols2 = np.random.randint(6, size=10)
data2 = np.random.randint(10, size=10)

print(np.array([rows2, cols2, data2]))

coo_arr2 = sparse.coo_array((data2, (rows2, cols2)), shape=(10, 6))
csr_arr2 = coo_arr2.tocsr()
coo_arr2.toarray()

[[0 1 5 2 4 2 3 2 0 0]
 [4 0 0 0 0 1 5 0 2 0]
 [2 8 9 7 4 5 4 6 0 4]]


array([[ 4,  0,  0,  0,  2,  0],
       [ 8,  0,  0,  0,  0,  0],
       [13,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  4],
       [ 4,  0,  0,  0,  0,  0],
       [ 9,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [18]:
(csr_arr1 @ csr_arr2.T).toarray()

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 12,   8,  13,   0,   4,   9,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 32,  64, 129,   0,  32,  72,   0,   0,   0,   0],
       [ 16,  16,  26,   0,   8,  18,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [19]:
type(sparse.vstack([coo_arr1, coo_arr2]))

scipy.sparse._coo.coo_matrix

In [20]:
sparse.vstack([coo_arr1, coo_arr2]).toarray()

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 8,  5,  0,  0,  0,  0],
       [ 2,  0,  0,  2,  4,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 4,  0,  0,  0,  2,  0],
       [ 8,  0,  0,  0,  0,  0],
       [13,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  4],
       [ 4,  0,  0,  0,  0,  0],
       [ 9,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [21]:
csr_arr1[[0], :].toarray()

array([[0, 0, 0, 0, 0, 0]])

In [22]:
seq = [csr_arr1] * 5
sparse.vstack(seq)

<50x6 sparse matrix of type '<class 'numpy.int64'>'
	with 45 stored elements in Compressed Sparse Row format>

In [23]:
rows3 = np.random.randint(6, size=10)
cols3 = np.random.randint(6, size=10)
data3 = np.random.randint(10, size=10)

print(np.array([rows3, cols3, data3]))

coo_mat = sparse.coo_matrix((data2, (rows2, cols2)), shape=(10, 6))
csr_mat = coo_mat.tocsr()
csr_mat.toarray()

[[3 4 2 0 2 3 3 0 4 2]
 [3 5 2 1 3 5 2 2 5 0]
 [1 1 1 0 8 2 6 4 1 4]]


array([[ 4,  0,  0,  0,  2,  0],
       [ 8,  0,  0,  0,  0,  0],
       [13,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  4],
       [ 4,  0,  0,  0,  0,  0],
       [ 9,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [24]:
csr_mat

<10x6 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [25]:
A = np.ones((5, 5))
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
S = sparse.csr_matrix(A)
S

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 25 stored elements in Compressed Sparse Row format>